services:
  - type: web
    name: real-estate-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    healthCheckPath: /api/test
    disk:
      name: uploads
      mountPath: /opt/render/project/src/backend/uploads
      sizeGB: 5
    envVars:
      - key: NODE_VERSION
        value: 18
      # Set these in the Render Dashboard with your DB credentials
      - key: MYSQL_HOST
        sync: false
      - key: MYSQL_USER
        sync: false
      - key: MYSQL_PASSWORD
        sync: false
      - key: MYSQL_DATABASE
        sync: false
      - key: MYSQL_PORT
        sync: false

